#!/usr/bin/env python

import subprocess
import configparser
import os.path
import sys

if __name__ == '__main__':
    parser = configparser.ConfigParser()
    parser._interpolation = configparser.ExtendedInterpolation()
    if not os.path.isfile('config.ini'):
        raise Exception('Error: No configuration found')

    parser.read('config.ini')
    sections = parser.sections()
    pipeline_name = sys.argv[1]
    tasks = parser.get('pipeline ' + pipeline_name, 'tasks').split()
    task_output = ''

    for task in tasks:
        task_key = 'task ' + task

        inputs = parser.get(task_key, 'input')
        if inputs == 'STDIN':
            inputs = task_output.split()
            inputs = ' '.join(inputs)

        command = parser.get(task_key, 'file')
        print 'Running {}...'.format(command)

        if parser.has_option(task_key, 'parallel') and parser.get(task_key, 'parallel') == 'true':
            inputs = inputs.split()
            commands = []
            for input in inputs:
                commands.append(command + ' ' + input)

            processes = []
            for command in commands:
                process = subprocess.Popen(command, shell=True)
                processes.append(process)

            for process in processes:
                output, _ = process.communicate()
                if type(output) is str:
                    task_output += output + '\n'

        else:
            command += ' ' + inputs
            task_output = subprocess.check_output(command, shell=True)

        print 'Task {} finished'.format(parser.get(task_key, 'file'))

    print task_output 
    
     


